import "./globals.css";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Coco Ease - Growing Stronger Together",
  description: "Generated by create next app",

  icons:{
    icon:"./favicon.png"
  }
};


const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100','200','300','400', '500','600', '700','800','900'],
    style: 'normal',
  
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
